

version: "3.7"
services:
    web_proxy:
        image: envoyproxy/envoy:v1.22-latest
        container_name: proxyWeb
        ports:
            - "8080:8080"
            - "9901:9901"
        volumes:
            - "./envoy.yaml:/etc/envoy/envoy.yaml:ro"

